/*
 * Copyright (c) 2006-2025 Chris Collins
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.hitorro.example.controllers;

import com.hitorro.example.controllers.DocumentManagementController.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.ActiveProfiles;

import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Spring Boot integration tests for DocumentManagementController.
 * 
 * <p>These tests run with full Spring context and actual DMS session factory.
 * Requires the application to have DMS enabled in configuration.
 */
@SpringBootTest
@ActiveProfiles("test")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class DocumentManagementControllerIntegrationTest {
    
    @Autowired
    private DocumentManagementController controller;
    
    private Long createdDocumentId;
    private Long testDocumentId;
    
    @BeforeAll
    void checkSetup() {
        if (controller == null) {
            System.out.println("WARNING: DocumentManagementController not available - tests will be skipped");
        }
    }
    
    @Test
    @Order(1)
    @DisplayName("Controller should be autowired")
    void testControllerAvailable() {
        // This test will pass even if controller is null (required=false)
        // Just checking Spring context loaded
        assertNotNull(controller, "Controller should be autowired when DMS is enabled");
    }
    
    @Test
    @Order(2)
    @DisplayName("Create document - should succeed with valid request")
    void testCreateDocument() {
        if (controller == null) {
            System.out.println("Skipping - controller not available");
            return;
        }
        
        CreateDocumentRequest request = new CreateDocumentRequest();
        request.setTitle("Integration Test Document");
        request.setNote("Created by integration test");
        request.setCreator("integration-test");
        request.setRealm("test");
        
        List<CategoryRequest> categories = new ArrayList<>();
        CategoryRequest cat = new CategoryRequest();
        cat.setDomain("test-type");
        cat.setValue("integration");
        categories.add(cat);
        request.setCategories(categories);
        
        ResponseEntity<DocumentResponse> response = controller.createDocument(request);
        
        assertEquals(HttpStatus.CREATED, response.getStatusCode(), 
                    "Document creation should return 201");
        
        DocumentResponse doc = response.getBody();
        assertNotNull(doc, "Response body should not be null");
        assertNotNull(doc.getId(), "Document should have an ID");
        assertNotNull(doc.getGuid(), "✓ Document has GUID - OnTrigger system is working!");
        assertEquals("Integration Test Document", doc.getTitle());
        
        System.out.println("✓ GUID generated by trigger: " + doc.getGuid());
        System.out.println("✓ OnTrigger system is working correctly!");
        
        // Save for later tests
        createdDocumentId = doc.getId();
        
        System.out.println("✓ Created document ID: " + createdDocumentId);
    }
    
    @Test
    @Order(3)
    @DisplayName("Get document - should retrieve created document")
    void testGetDocument() {
        if (controller == null || createdDocumentId == null) {
            System.out.println("Skipping - prerequisites not met");
            return;
        }
        
        ResponseEntity<DocumentResponse> response = controller.getDocument(createdDocumentId);
        
        assertEquals(HttpStatus.OK, response.getStatusCode());
        
        DocumentResponse doc = response.getBody();
        assertNotNull(doc);
        assertEquals(createdDocumentId, doc.getId());
        assertEquals("Integration Test Document", doc.getTitle());
        
        System.out.println("✓ Retrieved document: " + doc.getTitle());
    }
    
    @Test
    @Order(4)
    @DisplayName("Update document - should modify properties")
    void testUpdateDocument() {
        if (controller == null || createdDocumentId == null) {
            System.out.println("Skipping - prerequisites not met");
            return;
        }
        
        UpdateDocumentRequest request = new UpdateDocumentRequest();
        request.setTitle("Updated Integration Test Document");
        request.setNote("Modified by integration test");
        
        ResponseEntity<DocumentResponse> response = controller.updateDocument(createdDocumentId, request);
        
        assertEquals(HttpStatus.OK, response.getStatusCode());
        
        DocumentResponse doc = response.getBody();
        assertNotNull(doc);
        assertEquals("Updated Integration Test Document", doc.getTitle());
        assertEquals("Modified by integration test", doc.getNote());
        
        System.out.println("✓ Updated document title");
    }
    
    @Test
    @Order(5)
    @DisplayName("Add category - should attach category to document")
    void testAddCategory() {
        if (controller == null || createdDocumentId == null) {
            System.out.println("Skipping - prerequisites not met");
            return;
        }
        
        CategoryRequest request = new CategoryRequest();
        request.setDomain("priority");
        request.setValue("high");
        
        ResponseEntity<Map<String, Object>> response = 
                controller.addCategory(createdDocumentId, request);
        
        assertEquals(HttpStatus.OK, response.getStatusCode());
        
        Map<String, Object> result = response.getBody();
        assertNotNull(result);
        assertEquals("success", result.get("status"));
        
        System.out.println("✓ Added category: priority=high");
    }
    
    @Test
    @Order(6)
    @DisplayName("Query documents - should find by title")
    void testQueryDocuments() {
        if (controller == null || createdDocumentId == null) {
            System.out.println("Skipping - prerequisites not met");
            return;
        }
        
        QueryRequest request = new QueryRequest();
        request.setTitle("Integration Test");
        request.setMaxResults(10);
        
        ResponseEntity<List<DocumentResponse>> response = controller.queryDocuments(request);
        
        assertEquals(HttpStatus.OK, response.getStatusCode());
        
        List<DocumentResponse> documents = response.getBody();
        assertNotNull(documents);
        assertTrue(documents.size() > 0, "Should find at least one document");
        
        // Check our document is in the results
        boolean found = documents.stream()
                .anyMatch(d -> d.getId().equals(createdDocumentId));
        assertTrue(found, "Created document should be in query results");
        
        System.out.println("✓ Query found " + documents.size() + " document(s)");
    }
    
    @Test
    @Order(7)
    @DisplayName("Search by category - should find categorized documents")
    void testSearchByCategory() {
        if (controller == null || createdDocumentId == null) {
            System.out.println("Skipping - prerequisites not met");
            return;
        }
        
        ResponseEntity<List<DocumentResponse>> response = 
                controller.searchByCategory("priority", "high");
        
        assertEquals(HttpStatus.OK, response.getStatusCode());
        
        List<DocumentResponse> documents = response.getBody();
        assertNotNull(documents);
        
        System.out.println("✓ Category search found " + documents.size() + " document(s)");
    }
    
    @Test
    @Order(8)
    @DisplayName("Create version - should create new version of document")
    void testCreateVersion() {
        if (controller == null || createdDocumentId == null) {
            System.out.println("Skipping - prerequisites not met");
            return;
        }
        
        VersionRequest request = new VersionRequest();
        request.setNote("Version 1.1 created by integration test");
        
        ResponseEntity<DocumentResponse> response = 
                controller.createVersion(createdDocumentId, request);
        
        assertEquals(HttpStatus.CREATED, response.getStatusCode());
        
        DocumentResponse newVersion = response.getBody();
        assertNotNull(newVersion);
        assertNotEquals(createdDocumentId, newVersion.getId(), 
                       "New version should have different ID");
        assertEquals(createdDocumentId, newVersion.getCanonicalId(),
                    "New version should reference original as canonical");
        
        System.out.println("✓ Created version: " + newVersion.getVersionLabel());
    }
    
    @Test
    @Order(9)
    @DisplayName("Get version history - should show all versions")
    void testGetVersionHistory() {
        if (controller == null || createdDocumentId == null) {
            System.out.println("Skipping - prerequisites not met");
            return;
        }
        
        ResponseEntity<List<VersionInfo>> response = 
                controller.getVersionHistory(createdDocumentId);
        
        assertEquals(HttpStatus.OK, response.getStatusCode());
        
        List<VersionInfo> versions = response.getBody();
        assertNotNull(versions);
        assertTrue(versions.size() >= 1, "Should have at least one version");
        
        System.out.println("✓ Version history has " + versions.size() + " version(s)");
    }
    
    @Test
    @Order(10)
    @DisplayName("List content - should return empty list for new document")
    void testListContent() {
        if (controller == null || createdDocumentId == null) {
            System.out.println("Skipping - prerequisites not met");
            return;
        }
        
        ResponseEntity<List<ContentResponse>> response = 
                controller.listContent(createdDocumentId);
        
        assertEquals(HttpStatus.OK, response.getStatusCode());
        
        List<ContentResponse> content = response.getBody();
        assertNotNull(content);
        // New document should have no content
        assertEquals(0, content.size(), "New document should have no content");
        
        System.out.println("✓ Content list retrieved (empty as expected)");
    }
    
    @Test
    @Order(11)
    @DisplayName("Remove category - should detach category from document")
    void testRemoveCategory() {
        if (controller == null || createdDocumentId == null) {
            System.out.println("Skipping - prerequisites not met");
            return;
        }
        
        ResponseEntity<Map<String, Object>> response = 
                controller.removeCategory(createdDocumentId, "priority", "high");
        
        assertEquals(HttpStatus.OK, response.getStatusCode());
        
        Map<String, Object> result = response.getBody();
        assertNotNull(result);
        assertEquals("success", result.get("status"));
        
        System.out.println("✓ Removed category: priority=high");
    }
    
    @Test
    @Order(90)
    @DisplayName("Error handling - should return 404 for non-existent document")
    void testGetNonExistentDocument() {
        if (controller == null) {
            System.out.println("Skipping - controller not available");
            return;
        }
        
        ResponseEntity<DocumentResponse> response = controller.getDocument(999999L);
        
        assertEquals(HttpStatus.NOT_FOUND, response.getStatusCode(),
                    "Should return 404 for non-existent document");
        
        System.out.println("✓ Correctly returns 404 for non-existent document");
    }
    
    @Test
    @Order(91)
    @DisplayName("Error handling - should handle invalid query gracefully")
    void testInvalidQuery() {
        if (controller == null) {
            System.out.println("Skipping - controller not available");
            return;
        }
        
        QueryRequest request = new QueryRequest();
        request.setMaxResults(-1); // Invalid
        
        ResponseEntity<List<DocumentResponse>> response = controller.queryDocuments(request);
        
        // Should not crash, either returns results or error
        assertNotNull(response);
        assertTrue(response.getStatusCode() == HttpStatus.OK || 
                  response.getStatusCode() == HttpStatus.INTERNAL_SERVER_ERROR);
        
        System.out.println("✓ Handles invalid query parameters");
    }
    
    @Test
    @Order(99)
    @DisplayName("Cleanup - delete test document")
    void testDeleteDocument() {
        if (controller == null || createdDocumentId == null) {
            System.out.println("Skipping cleanup - prerequisites not met");
            return;
        }
        
        ResponseEntity<Map<String, Object>> response = 
                controller.deleteDocument(createdDocumentId);
        
        assertEquals(HttpStatus.OK, response.getStatusCode());
        
        Map<String, Object> result = response.getBody();
        assertNotNull(result);
        assertEquals("success", result.get("status"));
        
        // Verify deletion
        ResponseEntity<DocumentResponse> getResponse = controller.getDocument(createdDocumentId);
        assertEquals(HttpStatus.NOT_FOUND, getResponse.getStatusCode(),
                    "Deleted document should not be found");
        
        System.out.println("✓ Deleted test document ID: " + createdDocumentId);
    }
    
    @Test
    @Order(100)
    @DisplayName("Complete workflow - create, modify, version, and delete")
    void testCompleteWorkflow() {
        if (controller == null) {
            System.out.println("Skipping workflow test - controller not available");
            return;
        }
        
        System.out.println("\n=== Starting Complete Workflow Test ===\n");
        
        // 1. Create
        CreateDocumentRequest createReq = new CreateDocumentRequest();
        createReq.setTitle("Workflow Test Document");
        createReq.setCreator("workflow-test");
        
        ResponseEntity<DocumentResponse> createResp = controller.createDocument(createReq);
        assertEquals(HttpStatus.CREATED, createResp.getStatusCode());
        testDocumentId = createResp.getBody().getId();
        System.out.println("1. Created document: " + testDocumentId);
        
        // 2. Add categories
        CategoryRequest cat1 = new CategoryRequest();
        cat1.setDomain("workflow");
        cat1.setValue("test");
        controller.addCategory(testDocumentId, cat1);
        System.out.println("2. Added category");
        
        // 3. Update
        UpdateDocumentRequest updateReq = new UpdateDocumentRequest();
        updateReq.setTitle("Updated Workflow Document");
        controller.updateDocument(testDocumentId, updateReq);
        System.out.println("3. Updated title");
        
        // 4. Create version
        VersionRequest versionReq = new VersionRequest();
        versionReq.setNote("Version 1.1");
        ResponseEntity<DocumentResponse> versionResp = 
                controller.createVersion(testDocumentId, versionReq);
        assertEquals(HttpStatus.CREATED, versionResp.getStatusCode());
        System.out.println("4. Created version");
        
        // 5. Query
        QueryRequest queryReq = new QueryRequest();
        queryReq.setTitle("Workflow");
        ResponseEntity<List<DocumentResponse>> queryResp = controller.queryDocuments(queryReq);
        assertTrue(queryResp.getBody().size() > 0);
        System.out.println("5. Queried documents: found " + queryResp.getBody().size());
        
        // 6. Get version history
        ResponseEntity<List<VersionInfo>> historyResp = 
                controller.getVersionHistory(testDocumentId);
        assertTrue(historyResp.getBody().size() >= 1);
        System.out.println("6. Retrieved version history: " + historyResp.getBody().size() + " versions");
        
        // 7. Delete
        ResponseEntity<Map<String, Object>> deleteResp = 
                controller.deleteDocument(testDocumentId);
        assertEquals(HttpStatus.OK, deleteResp.getStatusCode());
        System.out.println("7. Deleted document");
        
        System.out.println("\n=== Workflow Test Complete ===\n");
    }
}
