apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hitorro-example-springboot
    app.kubernetes.io/managed-by: devportal
  name: hitorro-example-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hitorro-example-springboot
  template:
    metadata:
      labels:
        app: hitorro-example-springboot
    spec:
      containers:
      - name: hitorro-example-springboot
        image: devportal/hitorro-example-springboot:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: HT_BIN
          value: /opt/hitorro
        - name: HT_HOME
          value: /var/lib/hitorro
        volumeMounts:
        - name: ht-bin
          mountPath: /opt/hitorro
        - name: ht-home
          mountPath: /var/lib/hitorro
        readinessProbe:
          periodSeconds: 10
          initialDelaySeconds: 60
          failureThreshold: 12
          httpGet:
            path: /actuator/health
            port: http
      volumes:
      - name: ht-bin
        hostPath:
          path: /Users/chris/hitorro
          type: Directory
      - name: ht-home
        hostPath:
          path: /Users/chris/hthome
          type: Directory
