apiVersion: v1
kind: Service
metadata:
  labels:
    app: hitorro-example-springboot
    app.kubernetes.io/managed-by: devportal
  name: hitorro-example-springboot
spec:
  type: NodePort
  selector:
    app: hitorro-example-springboot
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
    nodePort: 30008
